add AWS support for DeleteIntermediateFiles task
broadinstitute/gatk-sv pull request #115
Opened 2021-02-19 14:18 UTC by henriqueribeiro

Add support for AWS in `DeleteIntermediateFiles` task in `Module00a`.

2021-02-26 16:15 UTC, mwalker174 requested changes
Thanks for this @henriqueribeiro ! We do need to have the input templates in `/test_input_templates` updated as well (`batch`, `module00a`, and `single-sample` I believe). You can validate that all generated inputs are valid using `scripts/test/validate.sh`.

2021-02-26 16:15 UTC, mwalker174 commented on wdl/Module00a.wdl
> +    String cloud_sdk_docker
Can you add a comment here suggesting which images to use for GCS and AWS?

2021-02-26 17:03 UTC, henriqueribeiro commented
I believe we need to update the `scripts/test/validate.sh`. It seems outdated and not working correctly. Do you confirm it needs some work?

2021-02-26 17:16 UTC, mwalker174 commented
@henriqueribeiro It appears the script is working correctly, but there are 2 errors in the WDLs that cause it to fail immediately. I've created PR #118 to fix that.

2021-02-26 20:23 UTC, henriqueribeiro commented
@mwalker174 all tests pass now :)

2021-03-03 20:38 UTC, mwalker174 approved these changes
Great, looks good to me!

2021-03-03 20:38 UTC, merged