Early baf generation
broadinstitute/gatk-sv pull request #351
Opened 2022-06-02 16:45 UTC by tedsharpe

2022-06-02 16:54 UTC, tedsharpe commented
![VCF_QC 1000G_Sudmant_ALL callset_benchmarking](https://user-images.githubusercontent.com/9284156/171683213-220c2855-fd48-4813-ab7d-ec08fede8a9a.png)
[VCF_QC.freq_distributions.merged.pdf](https://github.com/broadinstitute/gatk-sv/files/8825940/VCF_QC.freq_distributions.merged.pdf)
![VCF_QC genotype_distributions](https://user-images.githubusercontent.com/9284156/171683232-a7b83355-6722-4aff-841c-776585351aa4.png)
[VCF_QC.size_distributions.merged.pdf](https://github.com/broadinstitute/gatk-sv/files/8825941/VCF_QC
[VCF_QC.SV_counts.merged.pdf](https://github.com/broadinstitute/gatk-sv/files/8825942/VCF_QC.SV_counts.merged.pdf)
.size_dist
![VCF_QC SV_per_genome](https://user-images.githubusercontent.com/9284156/171683261-772dd87e-f7fc-41af-bc1d-2deb3187259b.png)
ributions.merged.pdf)

2022-06-02 17:10 UTC, tedsharpe commented
[svtest.txt](https://github.com/broadinstitute/gatk-sv/files/8826043/svtest.txt)

2022-06-06 23:52 UTC, tedsharpe commented
This is not quite ready to go.  I need to make a few updates due to the LD --> SD renaming.

2022-06-07 20:15 UTC, mwalker174 requested changes
@tedsharpe it's like music to my ears. Benchmarks check out, just a few requests.

Thanks for updating the README. I think there are a few spots that need updating still - searching "gvcf" shows there are a few references that can be deleted.

Edit: also, the LD files were a bit larger than I was hoping for at ~300MB. I think it's tenable for now. I have a new sites list generated from gnomAD that's almost ready and might be able to cut that in half, but let's save it for another PR.

2022-06-07 20:15 UTC, mwalker174 commented on wdl/BatchEvidenceMerging.wdl
> -    }
Deleting these from the main pipeline is definitely the right move at this point. However, we still need a means of changing sample IDs in evidence files for some projects. Can you add a new `SetSampleIdLegacy` workflow that takes in an SR, PE, and BAF file for a single sample and converts the sample ID in each file?

Also can you update the `Sample ID requirements` section of the README and include a pointer to the `SetSampleIdLegacy` workflow for evidence files generated with previous versions of the pipeline?

2022-06-21 15:38 UTC, mwalker174 commented
> 1. Have to wait until gatk/tws_bafFixes is available as a docker image (or I could make one) and update dockers.json.

Yes you could move the nightly (https://hub.docker.com/r/broadinstitute/gatk-nightly) after you merge onto GCR and use that.

> 2. I can't find superfluous mentions of gcnv as mentioned in the 1st review comment:  the references in wdl inputs appear to me to be downstream of BAF generation where we're using the pre-built random forest model to evaluate new samples.  @mwalker174: Can you point me to an example or two and I'll try to clean up the rest by analogy.

Was just pointing out `gvcf` (since those are no longer needed) not `gcnv`.

2022-06-22 15:54 UTC, tedsharpe commented
Updated dockers.json to point to a gatk image that has the is consistent with current head of master (having just checked in that small bug fix).  Eliminated gvcf references.  I think we're good to go.

2022-06-23 14:46 UTC, mwalker174 approved these changes
Thank you @tedsharpe I think it's almost ready! I still see some gVCF occurrences in the README if you could just take those out, then good to merge.

2022-06-23 15:20 UTC, merged