Improve cromwell monitoring script
broadinstitute/gatk-sv pull request #5
Opened 2020-06-29 15:27 UTC by TedBrookings

* Added new cromwell monitoring script:
  /scripts/cromwell/cromwell_monitoring_script2.sh
  Outputs resource log in tabular format that 
  * uses less disk space
  * (is thus hopefully more likely to de-localize after job completion)
  * is easier to visually scan
  * is easier to ingest and process via script
* Added new script to extract summary info from new logs:
  /scripts/cromwell/get_cromwell_resource_usage2.sh 
  This script can process local or remote logs, and can select logs via
  cloud path, local path, or cromwell workflow ID

2020-08-28 20:17 UTC, TedBrookings commented on scripts/cromwell/get_cromwell_resource_usage2.sh
> +      gsutil -m ls "$TOP_DIR/**monitoring.log" 2>/dev/null || echo ""
I added code to remove trailing slashes from the input WORKFLOW_INFO when it's a cloud or local path. I tested it both with and without extra slashes and it appeared to work.

The other error you mentioned was: if you supplied options that bypasses the (no input arguments) check at the beginning of the script. If you forgot to supply WORKFLOW_INFO, it default to empty, isn't a path, and gets interpreted as an empty WORKFLOW_ID. Cromshell gets the last workflow when you pass it an empty workflow ID. I addressed this by checking for an empty WORKFLOW_INFO and throwing an error. I also moved around some (trivial) output to stderr to make errors more clear.

2020-09-02 22:43 UTC, TedBrookings commented
@epiercehoffman, following our offline conversation, I added an option to omit the second "units" header line, and I altered the monitoring script to make the header column names unique. I'm happy to wait until you have a chance to test these changes (I did but your test routine is doubtlessly different from mine). If you want me to just go ahead and merge, I can do that too.

2020-09-15 20:49 UTC, epiercehoffman requested changes
I am so sorry it took me this long to review your changes again, especially since you responded to my last review so quickly! Thanks so much for adding the option to hide the second units header line and for making the first header line have unique column names - that will make parsing the output of this script in python simpler for sure. 

I tested a whole bunch of combinations of arguments and had no trouble until `--hide-units`, which gets matched by the `^-+(h|help)` regex before it gets to `^-+(u|hide-units)`. This is certainly not a big deal as `-u` works perfectly, but for the aesthetic I have suggested changing the longer-form option to hide the units to `--no-units`, as that seemed to be the easiest way to deal with this problem. If you are satisfied with that change, then I think this is all set to merge - I tested the `--no-units` change already locally so I don't feel the need to do another round of testing.

2020-09-15 20:49 UTC, epiercehoffman commented on scripts/cromwell/get_cromwell_resource_usage2.sh
> +    elif [[ ${!i} =~ ^-+(u|hide-units) ]]; then
```suggestion
    elif [[ ${!i} =~ ^-+(u|no-units) ]]; then
```

2020-09-15 20:49 UTC, epiercehoffman commented on scripts/cromwell/get_cromwell_resource_usage2.sh
> +        -u --hide-units
```suggestion
        -u --no-units
```

2020-09-15 20:58 UTC, TedBrookings commented on scripts/cromwell/get_cromwell_resource_usage2.sh
> +        -u --hide-units
Good catch, and that's a good fix.

2020-09-15 21:05 UTC, epiercehoffman approved these changes

2020-09-15 21:07 UTC, merged